server:
  port: 8001
spring:
  application:
    name: cap-rest
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.168:8848
    sentinel:
      transport:
        port: 8719
        # sentinel流量监控台 不知道为什么docker上的监控不到本地应用
        # 可能需要监控台跟应用在同一台机器上？
        dashboard: 127.0.0.1:8080
      eager: true
