spring:
  application:
    name: rocketmq-consume-example
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.168:8848
    stream:
      rocketmq:
        bindings:
          input:
            consumer:
              orderly: true
#          input1:
#            consumer:
#              orderly: true
#          input2:
#            consumer:
#              orderly: false
#              tags: tagStr
        binder:
          name-server: 192.168.0.168:9876
      bindings:
        input:
          destination: test-topic
          content-type: application/json
          group: test-group
#        input1:
#          destination: test-topic
#          content-type: text/plain
#          group: test-group1
#        input2:
#          destination: test-topic
#          content-type: text/plain
#          group: test-group2
#          consumer:
#            concurrency: 20

server:
  port: 9094
management:
  endpoint:
    health:
      show-detailes: always
  endpoints:
    web:
      exposure:
        include: '*'
